project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: favicon.png
  navbar:
    background: dark
    logo: favicon.png
    right:
      - href: index.qmd
        text: about
      - href: research.qmd
        text: research
      - href: cv.qmd
        text: cv
  page-footer:
    # background: light # Options: light, dark, primary, or none
    left: "© 2026 Michael Cusack-Nelkin"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


