---
title: "Curriculum Vitae"
---

## Education

**Columbia University** | New York City, NY | Aug 2025 - Dec 2026

*M.A in Mathematics of Finance*

* GPA: 3.57 / 4.00
* Coursework: Statistical Aspects of Finance, Algorithmic Trading, Linear Regression Models, Advanced Machine Learning for Finance

**The College of William & Mary** | Williamsburg, VA | Aug 2018 - May 2022

*B.S in Physics, Minors in Data Science and Mathematics*

* GPA: 3.72 / 4.0
* Coursework: Advanced Applied Machine Learning, Quantum Mechanics I & II, Fluid Mechanics
* Honors: Dean's List, Magna Cum Laude

## Research and Publications

[*Optimal Portfolio Construction*]() | May 2026 - Present

* **Lead Author** – Working paper. Optimal portfolio construction.


[*Adaptive Execution Strategies Lead to Robust Improvements Over Naive Benchmark*](publications/saf_whitepaper.pdf)

* **Lead Author** – Designed an adaptive execution strategy using L2 order book data and an execution simulator to test it. The simulator can simulate the fills and impact of any generic fill strategy using market orders, resting limit orders, and IOC limit orders in the presences of variable latency, and book resilience (modeled as a Poisson process). Final strategy offered large improvements over naive strategies, using microstructure signals to adapt fill agrression.

## Work Experience

**Deloitte Consulting** | Austin, TX

*Deloitte Quantum AI Analyst* | Jan 2023 - Dec 2024

* **Client Pitching** – Pitched the firm's quantum computation and optimization capabilities in presentations to commercial clients from the finance and logistics sectors.
* **Quantum Optimization** – Built and presented Python demonstrations of Grover's quantum search algorithm using IBM Qiskit in Python and IBM simulators and quantum hardware.

*Business Technology Analyst, AI and Data* | Oct 2022 - Jun 2025

* **Tech Infrastructure** – Built modern web infrastructure for the Texas Office of the Inspector General, allowing them to more effectively manage, report, and archive $140,000,000 of annual Medicaid fraud recoveries.
* **Team Leadership** – Led a team of four software developers and testers and shipped a case processing system for Texas OIG to recover $10,000,000 of previously unrecoverable fraudulent claims upon deployment in 2023.

**Gilder Gagnon & Howe Co.** | New York, NY

*Securities Analysis Intern* | Feb 2018 - May 2018

* **Fundamental Analysis** – Assisted with fundamental analysis of publicly listed US businesses in the gaming industry. Analyzed 10K/10Q filings and core financial statements and summarized for equity analysts.
* **Stakeholder Participation** – Participated in investment committee meetings with portfolio company executives across the media, aggrotech, and biotech industries. Questioned executives' pitches and companies' financials. Took comprehensive notes for equity analysts and company management.

## Competitions

**Millennium x Columbia University Trading Competition** | New York, NY

*ETF Arbitrage Simulation* | Aug 2025

* **Leadership** – Led a team of four at an Millennium Managment ETF arbitrage competition for Mathematics of Finance students. Achieved 1st place measured by risk-adjusted returns.
